// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/modelfulx/v1alpha/modelmesh_service.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/imneov/modelmesh/mindspore_serving/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PredictRequest) Validate() error {
	if this.Mindspore != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Mindspore); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Mindspore", err)
		}
	}
	return nil
}
func (this *PredictReply) Validate() error {
	if this.Mindspore != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Mindspore); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Mindspore", err)
		}
	}
	return nil
}
