// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mindspore_serving/proto/ms_agent.proto

package mindspore_serving_proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *DistributedPredictRequest) Validate() error {
	for _, item := range this.Inputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Inputs", err)
			}
		}
	}
	return nil
}
func (this *DistributedPredictReply) Validate() error {
	for _, item := range this.Outputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Outputs", err)
			}
		}
	}
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
func (this *DistributedExitRequest) Validate() error {
	return nil
}
func (this *DistributedExitReply) Validate() error {
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
