// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mindspore_serving/proto/ms_distributed.proto

package mindspore_serving_proto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AgentSpec struct {
	RankId               int64         `protobuf:"varint,1,opt,name=rank_id,json=rankId,proto3" json:"rank_id,omitempty"`
	BatchSize            int64         `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Inputs               []*TensorInfo `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs              []*TensorInfo `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AgentSpec) Reset()         { *m = AgentSpec{} }
func (m *AgentSpec) String() string { return proto.CompactTextString(m) }
func (*AgentSpec) ProtoMessage()    {}
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{0}
}
func (m *AgentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentSpec.Unmarshal(m, b)
}
func (m *AgentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentSpec.Marshal(b, m, deterministic)
}
func (m *AgentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentSpec.Merge(m, src)
}
func (m *AgentSpec) XXX_Size() int {
	return xxx_messageInfo_AgentSpec.Size(m)
}
func (m *AgentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_AgentSpec proto.InternalMessageInfo

func (m *AgentSpec) GetRankId() int64 {
	if m != nil {
		return m.RankId
	}
	return 0
}

func (m *AgentSpec) GetBatchSize() int64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *AgentSpec) GetInputs() []*TensorInfo {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *AgentSpec) GetOutputs() []*TensorInfo {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type CommonModelMeta struct {
	ServableName          string           `protobuf:"bytes,1,opt,name=servable_name,json=servableName,proto3" json:"servable_name,omitempty"`
	ModelKey              string           `protobuf:"bytes,2,opt,name=model_key,json=modelKey,proto3" json:"model_key,omitempty"`
	WithBatchDim          bool             `protobuf:"varint,3,opt,name=with_batch_dim,json=withBatchDim,proto3" json:"with_batch_dim,omitempty"`
	WithoutBatchDimInputs []int64          `protobuf:"varint,4,rep,packed,name=without_batch_dim_inputs,json=withoutBatchDimInputs,proto3" json:"without_batch_dim_inputs,omitempty"`
	InputsCount           map[uint64]int64 `protobuf:"bytes,5,rep,name=inputs_count,json=inputsCount,proto3" json:"inputs_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	OutputsCount          map[uint64]int64 `protobuf:"bytes,6,rep,name=outputs_count,json=outputsCount,proto3" json:"outputs_count,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral  struct{}         `json:"-"`
	XXX_unrecognized      []byte           `json:"-"`
	XXX_sizecache         int32            `json:"-"`
}

func (m *CommonModelMeta) Reset()         { *m = CommonModelMeta{} }
func (m *CommonModelMeta) String() string { return proto.CompactTextString(m) }
func (*CommonModelMeta) ProtoMessage()    {}
func (*CommonModelMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{1}
}
func (m *CommonModelMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonModelMeta.Unmarshal(m, b)
}
func (m *CommonModelMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonModelMeta.Marshal(b, m, deterministic)
}
func (m *CommonModelMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonModelMeta.Merge(m, src)
}
func (m *CommonModelMeta) XXX_Size() int {
	return xxx_messageInfo_CommonModelMeta.Size(m)
}
func (m *CommonModelMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonModelMeta.DiscardUnknown(m)
}

var xxx_messageInfo_CommonModelMeta proto.InternalMessageInfo

func (m *CommonModelMeta) GetServableName() string {
	if m != nil {
		return m.ServableName
	}
	return ""
}

func (m *CommonModelMeta) GetModelKey() string {
	if m != nil {
		return m.ModelKey
	}
	return ""
}

func (m *CommonModelMeta) GetWithBatchDim() bool {
	if m != nil {
		return m.WithBatchDim
	}
	return false
}

func (m *CommonModelMeta) GetWithoutBatchDimInputs() []int64 {
	if m != nil {
		return m.WithoutBatchDimInputs
	}
	return nil
}

func (m *CommonModelMeta) GetInputsCount() map[uint64]int64 {
	if m != nil {
		return m.InputsCount
	}
	return nil
}

func (m *CommonModelMeta) GetOutputsCount() map[uint64]int64 {
	if m != nil {
		return m.OutputsCount
	}
	return nil
}

type DistributedModelMeta struct {
	RankSize             int64    `protobuf:"varint,1,opt,name=rank_size,json=rankSize,proto3" json:"rank_size,omitempty"`
	StageSize            int64    `protobuf:"varint,2,opt,name=stage_size,json=stageSize,proto3" json:"stage_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistributedModelMeta) Reset()         { *m = DistributedModelMeta{} }
func (m *DistributedModelMeta) String() string { return proto.CompactTextString(m) }
func (*DistributedModelMeta) ProtoMessage()    {}
func (*DistributedModelMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{2}
}
func (m *DistributedModelMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistributedModelMeta.Unmarshal(m, b)
}
func (m *DistributedModelMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistributedModelMeta.Marshal(b, m, deterministic)
}
func (m *DistributedModelMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributedModelMeta.Merge(m, src)
}
func (m *DistributedModelMeta) XXX_Size() int {
	return xxx_messageInfo_DistributedModelMeta.Size(m)
}
func (m *DistributedModelMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributedModelMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DistributedModelMeta proto.InternalMessageInfo

func (m *DistributedModelMeta) GetRankSize() int64 {
	if m != nil {
		return m.RankSize
	}
	return 0
}

func (m *DistributedModelMeta) GetStageSize() int64 {
	if m != nil {
		return m.StageSize
	}
	return 0
}

type AgentRegisterRequest struct {
	AgentSpec            []*AgentSpec `protobuf:"bytes,1,rep,name=agent_spec,json=agentSpec,proto3" json:"agent_spec,omitempty"`
	Address              string       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentRegisterRequest) Reset()         { *m = AgentRegisterRequest{} }
func (m *AgentRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*AgentRegisterRequest) ProtoMessage()    {}
func (*AgentRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{3}
}
func (m *AgentRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRegisterRequest.Unmarshal(m, b)
}
func (m *AgentRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRegisterRequest.Marshal(b, m, deterministic)
}
func (m *AgentRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRegisterRequest.Merge(m, src)
}
func (m *AgentRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_AgentRegisterRequest.Size(m)
}
func (m *AgentRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRegisterRequest proto.InternalMessageInfo

func (m *AgentRegisterRequest) GetAgentSpec() []*AgentSpec {
	if m != nil {
		return m.AgentSpec
	}
	return nil
}

func (m *AgentRegisterRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AgentRegisterReply struct {
	ErrorMsg             *ErrorMsg `protobuf:"bytes,1,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentRegisterReply) Reset()         { *m = AgentRegisterReply{} }
func (m *AgentRegisterReply) String() string { return proto.CompactTextString(m) }
func (*AgentRegisterReply) ProtoMessage()    {}
func (*AgentRegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{4}
}
func (m *AgentRegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRegisterReply.Unmarshal(m, b)
}
func (m *AgentRegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRegisterReply.Marshal(b, m, deterministic)
}
func (m *AgentRegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRegisterReply.Merge(m, src)
}
func (m *AgentRegisterReply) XXX_Size() int {
	return xxx_messageInfo_AgentRegisterReply.Size(m)
}
func (m *AgentRegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRegisterReply proto.InternalMessageInfo

func (m *AgentRegisterReply) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type AgentExitRequest struct {
	// Types that are valid to be assigned to AddressChoice:
	//
	//	*AgentExitRequest_Address
	//	*AgentExitRequest_AgentIp
	AddressChoice        isAgentExitRequest_AddressChoice `protobuf_oneof:"address_choice"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *AgentExitRequest) Reset()         { *m = AgentExitRequest{} }
func (m *AgentExitRequest) String() string { return proto.CompactTextString(m) }
func (*AgentExitRequest) ProtoMessage()    {}
func (*AgentExitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{5}
}
func (m *AgentExitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentExitRequest.Unmarshal(m, b)
}
func (m *AgentExitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentExitRequest.Marshal(b, m, deterministic)
}
func (m *AgentExitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentExitRequest.Merge(m, src)
}
func (m *AgentExitRequest) XXX_Size() int {
	return xxx_messageInfo_AgentExitRequest.Size(m)
}
func (m *AgentExitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentExitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentExitRequest proto.InternalMessageInfo

type isAgentExitRequest_AddressChoice interface {
	isAgentExitRequest_AddressChoice()
}

type AgentExitRequest_Address struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3,oneof"`
}
type AgentExitRequest_AgentIp struct {
	AgentIp string `protobuf:"bytes,2,opt,name=agent_ip,json=agentIp,proto3,oneof"`
}

func (*AgentExitRequest_Address) isAgentExitRequest_AddressChoice() {}
func (*AgentExitRequest_AgentIp) isAgentExitRequest_AddressChoice() {}

func (m *AgentExitRequest) GetAddressChoice() isAgentExitRequest_AddressChoice {
	if m != nil {
		return m.AddressChoice
	}
	return nil
}

func (m *AgentExitRequest) GetAddress() string {
	if x, ok := m.GetAddressChoice().(*AgentExitRequest_Address); ok {
		return x.Address
	}
	return ""
}

func (m *AgentExitRequest) GetAgentIp() string {
	if x, ok := m.GetAddressChoice().(*AgentExitRequest_AgentIp); ok {
		return x.AgentIp
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*AgentExitRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _AgentExitRequest_OneofMarshaler, _AgentExitRequest_OneofUnmarshaler, _AgentExitRequest_OneofSizer, []interface{}{
		(*AgentExitRequest_Address)(nil),
		(*AgentExitRequest_AgentIp)(nil),
	}
}

func _AgentExitRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*AgentExitRequest)
	// address_choice
	switch x := m.AddressChoice.(type) {
	case *AgentExitRequest_Address:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Address)
	case *AgentExitRequest_AgentIp:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.AgentIp)
	case nil:
	default:
		return fmt.Errorf("AgentExitRequest.AddressChoice has unexpected type %T", x)
	}
	return nil
}

func _AgentExitRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*AgentExitRequest)
	switch tag {
	case 1: // address_choice.address
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.AddressChoice = &AgentExitRequest_Address{x}
		return true, err
	case 2: // address_choice.agent_ip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.AddressChoice = &AgentExitRequest_AgentIp{x}
		return true, err
	default:
		return false, nil
	}
}

func _AgentExitRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*AgentExitRequest)
	// address_choice
	switch x := m.AddressChoice.(type) {
	case *AgentExitRequest_Address:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Address)))
		n += len(x.Address)
	case *AgentExitRequest_AgentIp:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.AgentIp)))
		n += len(x.AgentIp)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type AgentExitReply struct {
	ErrorMsg             *ErrorMsg `protobuf:"bytes,1,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentExitReply) Reset()         { *m = AgentExitReply{} }
func (m *AgentExitReply) String() string { return proto.CompactTextString(m) }
func (*AgentExitReply) ProtoMessage()    {}
func (*AgentExitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{6}
}
func (m *AgentExitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentExitReply.Unmarshal(m, b)
}
func (m *AgentExitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentExitReply.Marshal(b, m, deterministic)
}
func (m *AgentExitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentExitReply.Merge(m, src)
}
func (m *AgentExitReply) XXX_Size() int {
	return xxx_messageInfo_AgentExitReply.Size(m)
}
func (m *AgentExitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentExitReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentExitReply proto.InternalMessageInfo

func (m *AgentExitReply) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type AgentFailedRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentFailedRequest) Reset()         { *m = AgentFailedRequest{} }
func (m *AgentFailedRequest) String() string { return proto.CompactTextString(m) }
func (*AgentFailedRequest) ProtoMessage()    {}
func (*AgentFailedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{7}
}
func (m *AgentFailedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentFailedRequest.Unmarshal(m, b)
}
func (m *AgentFailedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentFailedRequest.Marshal(b, m, deterministic)
}
func (m *AgentFailedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentFailedRequest.Merge(m, src)
}
func (m *AgentFailedRequest) XXX_Size() int {
	return xxx_messageInfo_AgentFailedRequest.Size(m)
}
func (m *AgentFailedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentFailedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentFailedRequest proto.InternalMessageInfo

type AgentFailedReply struct {
	ErrorMsg             *ErrorMsg `protobuf:"bytes,1,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AgentFailedReply) Reset()         { *m = AgentFailedReply{} }
func (m *AgentFailedReply) String() string { return proto.CompactTextString(m) }
func (*AgentFailedReply) ProtoMessage()    {}
func (*AgentFailedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{8}
}
func (m *AgentFailedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentFailedReply.Unmarshal(m, b)
}
func (m *AgentFailedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentFailedReply.Marshal(b, m, deterministic)
}
func (m *AgentFailedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentFailedReply.Merge(m, src)
}
func (m *AgentFailedReply) XXX_Size() int {
	return xxx_messageInfo_AgentFailedReply.Size(m)
}
func (m *AgentFailedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentFailedReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentFailedReply proto.InternalMessageInfo

func (m *AgentFailedReply) GetErrorMsg() *ErrorMsg {
	if m != nil {
		return m.ErrorMsg
	}
	return nil
}

type AgentConfigAcquireRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentConfigAcquireRequest) Reset()         { *m = AgentConfigAcquireRequest{} }
func (m *AgentConfigAcquireRequest) String() string { return proto.CompactTextString(m) }
func (*AgentConfigAcquireRequest) ProtoMessage()    {}
func (*AgentConfigAcquireRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{9}
}
func (m *AgentConfigAcquireRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigAcquireRequest.Unmarshal(m, b)
}
func (m *AgentConfigAcquireRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigAcquireRequest.Marshal(b, m, deterministic)
}
func (m *AgentConfigAcquireRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigAcquireRequest.Merge(m, src)
}
func (m *AgentConfigAcquireRequest) XXX_Size() int {
	return xxx_messageInfo_AgentConfigAcquireRequest.Size(m)
}
func (m *AgentConfigAcquireRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigAcquireRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigAcquireRequest proto.InternalMessageInfo

type AgentConfigAcquireReply struct {
	RankTableContent     string                                   `protobuf:"bytes,1,opt,name=rank_table_content,json=rankTableContent,proto3" json:"rank_table_content,omitempty"`
	RankList             []*AgentConfigAcquireReply_OneRankConfig `protobuf:"bytes,2,rep,name=rank_list,json=rankList,proto3" json:"rank_list,omitempty"`
	CommonMeta           *CommonModelMeta                         `protobuf:"bytes,3,opt,name=common_meta,json=commonMeta,proto3" json:"common_meta,omitempty"`
	DistributedMeta      *DistributedModelMeta                    `protobuf:"bytes,4,opt,name=distributed_meta,json=distributedMeta,proto3" json:"distributed_meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *AgentConfigAcquireReply) Reset()         { *m = AgentConfigAcquireReply{} }
func (m *AgentConfigAcquireReply) String() string { return proto.CompactTextString(m) }
func (*AgentConfigAcquireReply) ProtoMessage()    {}
func (*AgentConfigAcquireReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{10}
}
func (m *AgentConfigAcquireReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigAcquireReply.Unmarshal(m, b)
}
func (m *AgentConfigAcquireReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigAcquireReply.Marshal(b, m, deterministic)
}
func (m *AgentConfigAcquireReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigAcquireReply.Merge(m, src)
}
func (m *AgentConfigAcquireReply) XXX_Size() int {
	return xxx_messageInfo_AgentConfigAcquireReply.Size(m)
}
func (m *AgentConfigAcquireReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigAcquireReply.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigAcquireReply proto.InternalMessageInfo

func (m *AgentConfigAcquireReply) GetRankTableContent() string {
	if m != nil {
		return m.RankTableContent
	}
	return ""
}

func (m *AgentConfigAcquireReply) GetRankList() []*AgentConfigAcquireReply_OneRankConfig {
	if m != nil {
		return m.RankList
	}
	return nil
}

func (m *AgentConfigAcquireReply) GetCommonMeta() *CommonModelMeta {
	if m != nil {
		return m.CommonMeta
	}
	return nil
}

func (m *AgentConfigAcquireReply) GetDistributedMeta() *DistributedModelMeta {
	if m != nil {
		return m.DistributedMeta
	}
	return nil
}

type AgentConfigAcquireReply_OneRankConfig struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	DeviceId             int64    `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentConfigAcquireReply_OneRankConfig) Reset()         { *m = AgentConfigAcquireReply_OneRankConfig{} }
func (m *AgentConfigAcquireReply_OneRankConfig) String() string { return proto.CompactTextString(m) }
func (*AgentConfigAcquireReply_OneRankConfig) ProtoMessage()    {}
func (*AgentConfigAcquireReply_OneRankConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_368556e09b1b5b18, []int{10, 0}
}
func (m *AgentConfigAcquireReply_OneRankConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig.Unmarshal(m, b)
}
func (m *AgentConfigAcquireReply_OneRankConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig.Marshal(b, m, deterministic)
}
func (m *AgentConfigAcquireReply_OneRankConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig.Merge(m, src)
}
func (m *AgentConfigAcquireReply_OneRankConfig) XXX_Size() int {
	return xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig.Size(m)
}
func (m *AgentConfigAcquireReply_OneRankConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AgentConfigAcquireReply_OneRankConfig proto.InternalMessageInfo

func (m *AgentConfigAcquireReply_OneRankConfig) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AgentConfigAcquireReply_OneRankConfig) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func init() {
	proto.RegisterType((*AgentSpec)(nil), "mindspore.serving.proto.AgentSpec")
	proto.RegisterType((*CommonModelMeta)(nil), "mindspore.serving.proto.CommonModelMeta")
	proto.RegisterMapType((map[uint64]int64)(nil), "mindspore.serving.proto.CommonModelMeta.InputsCountEntry")
	proto.RegisterMapType((map[uint64]int64)(nil), "mindspore.serving.proto.CommonModelMeta.OutputsCountEntry")
	proto.RegisterType((*DistributedModelMeta)(nil), "mindspore.serving.proto.DistributedModelMeta")
	proto.RegisterType((*AgentRegisterRequest)(nil), "mindspore.serving.proto.AgentRegisterRequest")
	proto.RegisterType((*AgentRegisterReply)(nil), "mindspore.serving.proto.AgentRegisterReply")
	proto.RegisterType((*AgentExitRequest)(nil), "mindspore.serving.proto.AgentExitRequest")
	proto.RegisterType((*AgentExitReply)(nil), "mindspore.serving.proto.AgentExitReply")
	proto.RegisterType((*AgentFailedRequest)(nil), "mindspore.serving.proto.AgentFailedRequest")
	proto.RegisterType((*AgentFailedReply)(nil), "mindspore.serving.proto.AgentFailedReply")
	proto.RegisterType((*AgentConfigAcquireRequest)(nil), "mindspore.serving.proto.AgentConfigAcquireRequest")
	proto.RegisterType((*AgentConfigAcquireReply)(nil), "mindspore.serving.proto.AgentConfigAcquireReply")
	proto.RegisterType((*AgentConfigAcquireReply_OneRankConfig)(nil), "mindspore.serving.proto.AgentConfigAcquireReply.OneRankConfig")
}

func init() {
	proto.RegisterFile("mindspore_serving/proto/ms_distributed.proto", fileDescriptor_368556e09b1b5b18)
}

var fileDescriptor_368556e09b1b5b18 = []byte{
	// 751 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdf, 0x4e, 0x3b, 0x45,
	0x14, 0xb6, 0x5d, 0x7e, 0xa5, 0x7b, 0x5a, 0xfa, 0xab, 0x93, 0x1a, 0xd6, 0x36, 0x24, 0xb8, 0x78,
	0xd1, 0x0b, 0x2c, 0x09, 0x5e, 0xa8, 0xa8, 0x18, 0x28, 0x18, 0x1b, 0x45, 0xcc, 0xc0, 0x85, 0x89,
	0x9a, 0xcd, 0x76, 0xf7, 0x50, 0x26, 0x74, 0x67, 0x96, 0x9d, 0x59, 0xb4, 0xbc, 0x80, 0x8f, 0xe5,
	0x3b, 0xf9, 0x04, 0x66, 0x66, 0x76, 0xdb, 0xf2, 0xa7, 0x04, 0x13, 0xee, 0x76, 0xbe, 0x73, 0xce,
	0x77, 0xfe, 0xec, 0x77, 0x66, 0x60, 0x37, 0x61, 0x3c, 0x96, 0xa9, 0xc8, 0x30, 0x90, 0x98, 0xdd,
	0x31, 0x3e, 0xd9, 0x4b, 0x33, 0xa1, 0xc4, 0x5e, 0x22, 0x83, 0x98, 0x49, 0x95, 0xb1, 0x71, 0xae,
	0x30, 0x1e, 0x18, 0x90, 0x6c, 0xce, 0xbd, 0x07, 0x85, 0xb7, 0x35, 0x74, 0xfb, 0x2f, 0xd0, 0x18,
	0x20, 0x42, 0xeb, 0xe9, 0xff, 0x53, 0x01, 0xf7, 0x68, 0x82, 0x5c, 0x5d, 0xa4, 0x18, 0x91, 0x4d,
	0x58, 0xcf, 0x42, 0x7e, 0x13, 0xb0, 0xd8, 0xab, 0x6c, 0x57, 0xfa, 0x0e, 0xad, 0xe9, 0xe3, 0x28,
	0x26, 0x5b, 0x00, 0xe3, 0x50, 0x45, 0xd7, 0x81, 0x64, 0xf7, 0xe8, 0x55, 0x8d, 0xcd, 0x35, 0xc8,
	0x05, 0xbb, 0x47, 0xf2, 0x35, 0xd4, 0x18, 0x4f, 0x73, 0x25, 0x3d, 0x67, 0xdb, 0xe9, 0x37, 0xf6,
	0x77, 0x06, 0x2b, 0x2a, 0x1b, 0x5c, 0x22, 0x97, 0x22, 0x1b, 0xf1, 0x2b, 0x41, 0x8b, 0x10, 0xf2,
	0x2d, 0xac, 0x8b, 0x5c, 0x99, 0xe8, 0xb5, 0xd7, 0x47, 0x97, 0x31, 0xfe, 0xbf, 0x0e, 0xbc, 0x1f,
	0x8a, 0x24, 0x11, 0xfc, 0x4c, 0xc4, 0x38, 0x3d, 0x43, 0x15, 0x92, 0x1d, 0xd8, 0xd0, 0x81, 0xe1,
	0x78, 0x8a, 0x01, 0x0f, 0x13, 0x34, 0xdd, 0xb8, 0xb4, 0x59, 0x82, 0x3f, 0x87, 0x09, 0x92, 0x1e,
	0xb8, 0x89, 0x8e, 0x08, 0x6e, 0x70, 0x66, 0x5a, 0x72, 0x69, 0xdd, 0x00, 0x3f, 0xe2, 0x8c, 0x7c,
	0x0a, 0xad, 0x3f, 0x99, 0xba, 0x0e, 0x6c, 0xd7, 0x31, 0x4b, 0x3c, 0x67, 0xbb, 0xd2, 0xaf, 0xd3,
	0xa6, 0x46, 0x8f, 0x35, 0x78, 0xc2, 0x12, 0xf2, 0x05, 0x78, 0xfa, 0x2c, 0x72, 0xb5, 0x70, 0x0c,
	0x8a, 0x49, 0xe8, 0x5e, 0x1c, 0xfa, 0x51, 0x61, 0x2f, 0x43, 0x46, 0xb6, 0xe7, 0xdf, 0xa1, 0x69,
	0xdd, 0x82, 0x48, 0xe4, 0x5c, 0x79, 0xef, 0x4c, 0xe3, 0x5f, 0xad, 0x6c, 0xfc, 0x51, 0x83, 0x03,
	0x4b, 0x33, 0xd4, 0xb1, 0xa7, 0x5c, 0x65, 0x33, 0xda, 0x60, 0x0b, 0x84, 0x04, 0xb0, 0x51, 0x4c,
	0xa7, 0xa0, 0xaf, 0x19, 0xfa, 0x83, 0x57, 0xd3, 0x9f, 0xdb, 0xe8, 0x25, 0xfe, 0xa6, 0x58, 0x82,
	0xba, 0x87, 0xd0, 0x7e, 0x5c, 0x01, 0x69, 0x83, 0xa3, 0x07, 0xa9, 0x27, 0xbd, 0x46, 0xf5, 0x27,
	0xe9, 0xc0, 0xbb, 0xbb, 0x70, 0x9a, 0x97, 0x7a, 0xb1, 0x87, 0x83, 0xea, 0x97, 0x95, 0xee, 0x77,
	0xf0, 0xe1, 0x93, 0x14, 0xff, 0x87, 0xc0, 0xa7, 0xd0, 0x39, 0x59, 0xac, 0xc3, 0xe2, 0xc7, 0xf7,
	0xc0, 0x35, 0x02, 0x36, 0x32, 0xb5, 0x12, 0xae, 0x6b, 0xc0, 0xa8, 0x74, 0x0b, 0x40, 0xaa, 0x70,
	0x82, 0x0f, 0x44, 0x6c, 0x10, 0x6d, 0xf6, 0x25, 0x74, 0xcc, 0x26, 0x50, 0x9c, 0x30, 0xa9, 0x30,
	0xa3, 0x78, 0x9b, 0xa3, 0x54, 0xe4, 0x08, 0x20, 0xd4, 0x78, 0x20, 0x53, 0x8c, 0xbc, 0x8a, 0x19,
	0xa5, 0xbf, 0x72, 0x94, 0xf3, 0x65, 0xa2, 0x6e, 0x38, 0xdf, 0x2b, 0x0f, 0xd6, 0xc3, 0x38, 0xce,
	0x50, 0xca, 0x42, 0x68, 0xe5, 0xd1, 0xbf, 0x04, 0xf2, 0x28, 0x69, 0x3a, 0x9d, 0x91, 0x43, 0x70,
	0x31, 0xcb, 0x44, 0x16, 0x24, 0x72, 0x62, 0xda, 0x68, 0xec, 0x7f, 0xb2, 0x32, 0xe3, 0xa9, 0xf6,
	0x3c, 0x93, 0x13, 0x5a, 0xc7, 0xe2, 0xcb, 0xff, 0x03, 0xda, 0x86, 0xf5, 0xf4, 0x2f, 0xa6, 0xca,
	0x36, 0xba, 0x8b, 0x1a, 0xcc, 0x36, 0xfc, 0xf0, 0xc1, 0xbc, 0x0a, 0xd2, 0x83, 0xba, 0x6d, 0x91,
	0xa5, 0xb6, 0x40, 0x63, 0xd4, 0xc8, 0x28, 0x3d, 0x6e, 0x43, 0xab, 0xf0, 0x0b, 0xa2, 0x6b, 0xc1,
	0x22, 0xf4, 0x7f, 0x81, 0xd6, 0x12, 0xfd, 0x5b, 0x14, 0xdc, 0x29, 0xc6, 0xf0, 0x7d, 0xc8, 0xa6,
	0x18, 0x17, 0x25, 0xfb, 0xb4, 0x68, 0xa3, 0x44, 0xdf, 0x22, 0x53, 0x0f, 0x3e, 0x36, 0x9c, 0x43,
	0xc1, 0xaf, 0xd8, 0xe4, 0x28, 0xba, 0xcd, 0x59, 0x86, 0x65, 0xc2, 0xbf, 0x1d, 0xd8, 0x7c, 0xce,
	0xaa, 0x13, 0xef, 0x02, 0x31, 0xd2, 0x52, 0xe6, 0x56, 0x89, 0x04, 0x57, 0xc8, 0x55, 0x71, 0xb1,
	0xb4, 0xb5, 0xe5, 0x52, 0x1b, 0x86, 0x16, 0x27, 0xbf, 0x15, 0x42, 0x9c, 0x32, 0xa9, 0xbc, 0xaa,
	0xd1, 0xcc, 0xe1, 0xcb, 0x9a, 0x79, 0x9a, 0x72, 0x70, 0xce, 0x91, 0x86, 0xfc, 0xc6, 0x5a, 0xac,
	0x90, 0x7f, 0x62, 0x52, 0x91, 0x11, 0x34, 0x22, 0xb3, 0xb1, 0x41, 0x82, 0x2a, 0x34, 0x37, 0x53,
	0x63, 0xbf, 0xff, 0xda, 0xed, 0xa6, 0x60, 0x83, 0xcd, 0xc2, 0xfc, 0x0a, 0xed, 0xa5, 0x77, 0xc5,
	0xf2, 0xad, 0x19, 0xbe, 0xcf, 0x56, 0xf2, 0x3d, 0xb7, 0x79, 0xf4, 0xfd, 0x12, 0x8d, 0x06, 0xba,
	0xdf, 0xc0, 0xc6, 0x83, 0xfa, 0x49, 0x0b, 0xaa, 0x2c, 0x2d, 0x06, 0x56, 0x65, 0xa9, 0xde, 0xd5,
	0x18, 0xf5, 0x53, 0xa4, 0x9f, 0x1b, 0xbb, 0x8d, 0x75, 0x0b, 0x8c, 0xe2, 0x71, 0xcd, 0xa4, 0xfa,
	0xfc, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x9c, 0x64, 0xe2, 0x11, 0x07, 0x00, 0x00,
}
