// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mindspore_serving/proto/ms_distributed.proto

package mindspore_serving_proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *AgentSpec) Validate() error {
	for _, item := range this.Inputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Inputs", err)
			}
		}
	}
	for _, item := range this.Outputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Outputs", err)
			}
		}
	}
	return nil
}
func (this *CommonModelMeta) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *DistributedModelMeta) Validate() error {
	return nil
}
func (this *AgentRegisterRequest) Validate() error {
	for _, item := range this.AgentSpec {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("AgentSpec", err)
			}
		}
	}
	return nil
}
func (this *AgentRegisterReply) Validate() error {
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
func (this *AgentExitRequest) Validate() error {
	return nil
}
func (this *AgentExitReply) Validate() error {
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
func (this *AgentFailedRequest) Validate() error {
	return nil
}
func (this *AgentFailedReply) Validate() error {
	if this.ErrorMsg != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ErrorMsg); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
		}
	}
	return nil
}
func (this *AgentConfigAcquireRequest) Validate() error {
	return nil
}
func (this *AgentConfigAcquireReply) Validate() error {
	for _, item := range this.RankList {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("RankList", err)
			}
		}
	}
	if this.CommonMeta != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CommonMeta); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CommonMeta", err)
		}
	}
	if this.DistributedMeta != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.DistributedMeta); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("DistributedMeta", err)
		}
	}
	return nil
}
func (this *AgentConfigAcquireReply_OneRankConfig) Validate() error {
	return nil
}
