// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mindspore_serving/proto/ms_service.proto

package mindspore_serving_proto

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PredictRequest) Validate() error {
	if this.ServableSpec != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ServableSpec); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ServableSpec", err)
		}
	}
	for _, item := range this.Instances {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Instances", err)
			}
		}
	}
	return nil
}
func (this *ErrorMsg) Validate() error {
	return nil
}
func (this *PredictReply) Validate() error {
	if this.ServableSpec != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ServableSpec); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ServableSpec", err)
		}
	}
	for _, item := range this.Instances {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Instances", err)
			}
		}
	}
	for _, item := range this.ErrorMsg {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ErrorMsg", err)
			}
		}
	}
	return nil
}
func (this *Instance) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *TensorShape) Validate() error {
	return nil
}
func (this *ShmTensorData) Validate() error {
	return nil
}
func (this *Tensor) Validate() error {
	if this.Shape != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Shape); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Shape", err)
		}
	}
	if oneOfNester, ok := this.GetTensorData().(*Tensor_ShmData); ok {
		if oneOfNester.ShmData != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.ShmData); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ShmData", err)
			}
		}
	}
	return nil
}
func (this *ServableSpec) Validate() error {
	return nil
}
func (this *PingRequest) Validate() error {
	return nil
}
func (this *PingReply) Validate() error {
	return nil
}
func (this *PongRequest) Validate() error {
	return nil
}
func (this *PongReply) Validate() error {
	return nil
}
func (this *TensorInfo) Validate() error {
	if this.Shape != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Shape); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Shape", err)
		}
	}
	return nil
}
