// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/inference/v2/grpc_predict_v2.proto

package inference

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ServerLiveRequest) Validate() error {
	return nil
}
func (this *ServerLiveResponse) Validate() error {
	return nil
}
func (this *ServerReadyRequest) Validate() error {
	return nil
}
func (this *ServerReadyResponse) Validate() error {
	return nil
}
func (this *ModelReadyRequest) Validate() error {
	return nil
}
func (this *ModelReadyResponse) Validate() error {
	return nil
}
func (this *ServerMetadataRequest) Validate() error {
	return nil
}
func (this *ServerMetadataResponse) Validate() error {
	return nil
}
func (this *ModelMetadataRequest) Validate() error {
	return nil
}
func (this *ModelMetadataResponse) Validate() error {
	for _, item := range this.Inputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Inputs", err)
			}
		}
	}
	for _, item := range this.Outputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Outputs", err)
			}
		}
	}
	return nil
}
func (this *ModelMetadataResponse_TensorMetadata) Validate() error {
	return nil
}
func (this *ModelInferRequest) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	for _, item := range this.Inputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Inputs", err)
			}
		}
	}
	for _, item := range this.Outputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Outputs", err)
			}
		}
	}
	return nil
}
func (this *ModelInferRequest_InferInputTensor) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	if this.Contents != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Contents); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Contents", err)
		}
	}
	return nil
}
func (this *ModelInferRequest_InferRequestedOutputTensor) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ModelInferResponse) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	for _, item := range this.Outputs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Outputs", err)
			}
		}
	}
	return nil
}
func (this *ModelInferResponse_InferOutputTensor) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	if this.Contents != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Contents); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Contents", err)
		}
	}
	return nil
}
func (this *InferParameter) Validate() error {
	return nil
}
func (this *InferTensorContents) Validate() error {
	return nil
}
func (this *RepositoryModelLoadRequest) Validate() error {
	return nil
}
func (this *RepositoryModelLoadResponse) Validate() error {
	return nil
}
func (this *RepositoryModelUnloadRequest) Validate() error {
	return nil
}
func (this *RepositoryModelUnloadResponse) Validate() error {
	return nil
}
